README: replace invalid examples
`brew alias up` doesn't work because `up` is an internal alias for
`brew update`.

    $ brew alias up=update
    Error: 'up' is a reserved command. Sorry.