lib/aliases: disallow aliases conflicting with dev cmds
We already disallow aliases that have the same name as a built-in
command, but we should also disallow aliases that conflict with
developer commands. They don't work since the internal commands take
precedence:

    $ brew alias bottle=install
    $ brew bottle hello
    Error: Formula not installed or up-to-date: hello